### ISSUE TITLE
To visualize...

### ISSUE THREAD

**Issue by taehyeong1001** [facebookresearch/assemblyhands-toolkit#10]
After validation, how and how do I visualize the results?

**Comment by tkhkaeio** [comment]
Please follow the function that visualizes given keypoints in camera and image coords.
https://github.com/facebookresearch/assemblyhands-toolkit/blob/ad20e4a37ec0bcde1f4e13338f6c25ef5ce25712/src/dataset/AssemblyHands-Ego/dataset.py#L354

**Comment by taehyeong1001** [comment]
The baseline's MPJPE result is over 100, does this mean the model is not trained?
![00](https://github.com/facebookresearch/assemblyhands-toolkit/assets/139948589/feafd6f3-7d34-4e31-97b0-6b3e89a19ac3)

**Comment by tkhkaeio** [comment]
I got a report for such behavior. IIRC, the running evaluation with 'train.py' has some bugs, but you may get correct results with 'test.py'. So, give me some time to fix it. Or if you resolve it, please do PR.
