### ISSUE TITLE
Does the current data matches the results in Table 4 of the CVPR 2023 paper?

### ISSUE THREAD

**Issue by ZYX-MLer** [facebookresearch/assemblyhands-toolkit#17]
Does the current data matches the results in Table 4 of the CVPR 2023 paper? Is this database manually labeled or automatically labeled?

**Comment by tkhkaeio** [comment]
There are implementation gaps between the paper report and this repo. 
In this codebase, 
1) val and test splits are different from the original paper.
2) public code is prepared using the InterHand repo, while the original implementation for the paper report is based on nonidentical internal code.
