### ISSUE TITLE
interacting hands criteria

### ISSUE THREAD

**Issue by ccchen091** [facebookresearch/assemblyhands-toolkit#19]
Hello, I found a problem when training your model, the types of hands detected in your model are all single hand, but when I open the dataset to observe, I find that there are many interactive hands, not just one-handed pictures, so I would like to ask you what is the problem?
“”“”“”“”“”“”
Get bbox and root depth from groundtruth annotation
Number of annotations in single hand sequences: 61153
Number of annotations in interacting hand sequences: 0
Number of skipped annotations: 387
“”“”“”“”“”“”“
![image](https://github.com/facebookresearch/assemblyhands-toolkit/assets/56759365/acdb987e-5a82-4377-8ec3-186a59469520)

**Comment by tkhkaeio** [comment]
In this codebase, we didn't assign the interacting label but rather created hand crops for each right and left hand. 
See [this line](https://github.com/facebookresearch/assemblyhands-toolkit/blob/f55a23c4b9ba1f412413f8279dd3aab52567bc99/src/dataset/AssemblyHands-Ego/dataset.py#L158C13-L158C68).

You can modify this data loader according to your criteria for interacting hands. For instance,

- compute the distance between two hands in a frame
- if the dist is less than a threshold, the interacting label is assigned.
- then create crops covering the two-hand region. 

I hope this can work for your case.
