### ISSUE TITLE
The dataset is too large to download.

### ISSUE THREAD

**Issue by xungeer29** [facebookresearch/assemblyhands-toolkit#2]
The dataset is too large to download. Is there any data with low fps available for download?

According to my estimation, the dataset is approximately 2.5T ......

**Comment by cavalleria** [comment]
Where did you see the link to download the data?

**Comment by xungeer29** [comment]
The download link was released last week, but it was deleted again this week.
















At 2023-06-06 20:02:44, "cavalleria" ***@***.***> wrote:

Where did you see the link to download the data?

**Comment by kunhe** [comment]
Hi, we have just updated the download link. Please check :)
