### ISSUE TITLE
action labels are missing in this repository

### ISSUE THREAD

**Issue by apple2373** [facebookresearch/assemblyhands-toolkit#20]
I spent some time to explore this repository and the provided json files because I wanted to find the action annotations used in experiments in the Section 5 of the paper, and I couldn't find it :) The only way I can think of is to go back to the original dataset of Assembly101, which is available here: https://github.com/assembly-101/assembly101-annotations

 I'm starting to do check that repository, but just sharing it here so that others won't do the same mistake....

**Comment by tkhkaeio** [comment]
Thank you for letting us know. Yep, action labels can be found on the Assembly101 work; we used the corresponding sequence name and frame ids.
