### ISSUE TITLE
Few questions regarding the dataset and training

### ISSUE THREAD

**Issue by Holiday888** [facebookresearch/assemblyhands-toolkit#3]
Thank you for your excellent work. I have a few questions regarding this repository.

Firstly, I was wondering if you could provide the training steps for the baseline model.

Secondly, I encountered an issue with the image training set "nusar-2021_action_both_9075-c08b_9075_user_id_2021-02-12_101609.tar.gz". It appears that there is an error when trying to decompress the file.

Lastly, I noticed that in the "dataset.py" file, the package "src.common.utils" is referenced, but it seems that the package is not included in this repository.

**Comment by kunhe** [comment]
hi, thanks for pointing it out. Indeed this tar file was not uploaded correctly.
We're at CVPR this week so it's a bit hard to re-upload. Will do it by this weekend.

**Comment by tkhkaeio** [comment]
Please follow the training protocol from InterHands and the utils are already updated.
