### ISSUE TITLE
Question on variables joint_valid, hand_type_valid and joint_coord

### ISSUE THREAD

**Issue by anjugopinath** [facebookresearch/assemblyhands-toolkit#6]
Hi,

I noticed that joint valid is mostly never all 1s even though most images have both hands and shape of joint coord is (42,3).
Does it mean that only joints with 1 are valid ?
<img width="471" alt="image" src="https://github.com/facebookresearch/assemblyhands-toolkit/assets/4654298/04928027-739d-4355-95bd-91c6a2a6e21d">
Also, what does hand type valid indicate? Are these variables explained somewhere?
<img width="139" alt="image" src="https://github.com/facebookresearch/assemblyhands-toolkit/assets/4654298/b01ee4cb-59f7-4fde-b1a4-ef1e3b281d6f">

**Comment by tkhkaeio** [comment]
The validity is computed from the visibility of keypoints from a view. If the hand is out-of-view, we don't have any cues to predict a pose from a given image. In this case, the score is all zeros.
