### ISSUE TITLE
Empty test set

### ISSUE THREAD

**Issue by gmindflow** [facebookresearch/assemblyhands-toolkit#8]
Hi, 

In the link you provided for downloading 'ego_images_rectified', the test set appears to be empty.
Could you check this issue please?

Thank you.

**Comment by gmindflow** [comment]
Also, running `python -m src.dataset.AssemblyHands-Ego.dataset`, I'm getting an error that:
"Load checkpoint not found /home/(user)/assemblyhands-toolkit/output/assemblyhands-ego/model_dump/snapshot_20.pth.tar" .

Is this error caused because the repository is supposed to have the snapshot_20.pth.tar file, or is it that I have some problems running the given code and the checkpoint is not created?

Could you give me some help please.

**Comment by tkhkaeio** [comment]
I've uploaded test data for ICCV HANDS challenge. Please see gdrive.

`output/assemblyhands-ego/model_dump` is the directory created after training.
Without it, you can use InterHands' checkpoint for the test.
https://github.com/facebookresearch/InterHand2.6M
